config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :groups, only: [:index, :show, :new, :create, :destroy]
    resources :records
  end

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  # Defines the root path route ("/")
  root to: 'splashes#index' 
end

app/models/group_record.rb
class GroupRecord < ApplicationRecord
  belongs_to :group
  belongs_to :record
end

app/controllers/group_records_controller.rb
class GroupRecordsController < ApplicationController
  before_action :set_group_record, only: %i[show edit update destroy]

  # GET /group_records or /group_records.json
  def index
    @group_records = GroupRecord.all
  end

  # GET /group_records/1 or /group_records/1.json
  def show; end

  # GET /group_records/new
  def new
    @group_record = GroupRecord.new
  end

  # GET /group_records/1/edit
  def edit; end

  # POST /group_records or /group_records.json
  def create
    @group_record = GroupRecord.new(group_record_params)

    respond_to do |format|
      if @group_record.save
        format.html { redirect_to group_record_url(@group_record), notice: 'Group record was successfully created.' }
        format.json { render :show, status: :created, location: @group_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_records/1 or /group_records/1.json
  def update
    respond_to do |format|
      if @group_record.update(group_record_params)
        format.html { redirect_to group_record_url(@group_record), notice: 'Group record was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_records/1 or /group_records/1.json
  def destroy
    @group_record.destroy

    respond_to do |format|
      format.html { redirect_to group_records_url, notice: 'Group record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_record
    @group_record = GroupRecord.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_record_params
    params.require(:group_record).permit(:group_id, :record_id)
  end
end

app/helpers/group_records_helper.rb
module GroupRecordsHelper
end

app/views/group_records/_form.html.erb
<%= form_with(model: group_record) do |form| %>
  <% if group_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_record.errors.count, "error") %> prohibited this group_record from being saved:</h2>

      <ul>
        <% group_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.number_field :group_id %>
  </div>

  <div>
    <%= form.label :record_id, style: "display: block" %>
    <%= form.number_field :record_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/group_records/_group_record.html.erb
<div id="<%= dom_id group_record %>">
  <p>
    <strong>Group:</strong>
    <%= group_record.group_id %>
  </p>

  <p>
    <strong>Record:</strong>
    <%= group_record.record_id %>
  </p>

</div>

app/views/group_records/edit.html.erb
<h1>Editing group record</h1>

<%= render "form", group_record: @group_record %>

<br>

<div>
  <%= link_to "Show this group record", @group_record %> |
  <%= link_to "Back to group records", group_records_path %>
</div>

app/views/group_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Group records</h1>

<div id="group_records">
  <% @group_records.each do |group_record| %>
    <%= render group_record %>
    <p>
      <%= link_to "Show this group record", group_record %>
    </p>
  <% end %>
</div>

<%= link_to "New group record", new_group_record_path %>

app/views/group_records/new.html.erb
<h1>New group record</h1>

<%= render "form", group_record: @group_record %>

<br>

<div>
  <%= link_to "Back to group records", group_records_path %>
</div>

app/views/group_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_record %>

<div>
  <%= link_to "Edit this group record", edit_group_record_path(@group_record) %> |
  <%= link_to "Back to group records", group_records_path %>

  <%= button_to "Destroy this group record", @group_record, method: :delete %>
</div>