config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :groups, only: [:index, :show, :new, :create, :destroy]
    resources :records
  end

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  # Defines the root path route ("/")
  root to: 'splashes#index' 
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :icon
  has_many :group_records, dependent: :destroy
  has_many :records, through: :group_records, dependent: :destroy

  validates :name, :icon, presence: true

  def amount
    amount = 0
    records.each { |record| amount += record.amount }
    amount
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
    @total_records = current_user.records.sum(:amount)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_groups_url(current_user, @group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to user_groups_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:user_id, :name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group, url: user_groups_path, method: :post do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mx-5">
    <% form.label :name, required: true, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <br />
  <div class="mx-5">
    <% form.label :icon, required: true, style: "display: block" %>
    <%= form.file_field :icon, direct_upload: true, class:"form-control", placeholder:"Icon" %>
  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :group_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div id="btn"class="btn btn-primary btn-lg  mt-4 mx-5">
    <%= form.submit class: 'bg-primary border border-0'%>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group_id py-1">
<div class="flex">
  <p>
   <%= group.amount %>
  </p>
  
  <p>
    <%= group.name %>
  </p>

  <div>
    <%= image_tag group.icon %>
  </div>
</div>

  <p class="my-3 text-center">
    <%= link_to "Show this group", user_group_path(current_user, group) %>
  </p>
 


</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="text-center welcome">
  <h6>Welcome <%= current_user.name %>, Here is a group of all your transaction </h6>
</div>

<h1 class="text-center text1">Group List</h1>
  <% if @groups.empty? %>
    <p class="text-center">No group added yet!</p>
  <% end %>

<div id="groups">
  <div class="text-center">
    <%= @total_records %>
  </div>
  <div>
    <% current_user.groups.each do |group| %>
      <%= render group %>
    <% end %>
  </div>

</div>
      <div class="text-center link-new">
        <%= link_to "Add New group", new_user_group_path(current_user, @groups) %>
      </div>
</div>

app/views/groups/new.html.erb
<h1 class="text-center">Add New group</h1>

<%= render "form", group: @group %>

<br>

<div class="mx-5 text-center link-new">
  <%= link_to "Back to groups", user_groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>
<div class="rec_btn my-5">
  <%= button_to "Delete this group", user_group_path, method: :delete, class: "btn btn-danger" %>
  <%= link_to "Add New record", new_user_record_path, class: "btn btn-secondary" %>
</div>
 

<div class="link-new text-center">
  <%= link_to "Back to groups", user_groups_path %>
</div>