config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :groups, only: [:index, :show, :new, :create, :destroy]
    resources :records
  end

  authenticated :user do
    root :to => 'groups#index', as: :authenticated_root
  end

  # Defines the root path route ("/")
  root to: 'splashes#index' 
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :group_records, dependent: :destroy
  has_many :groups, through: :group_records

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show edit update destroy]

  # GET /records or /records.json
  def index
    @records = Record.includes(:user).where(user: current_user).order(created_at: :desc)
  end

  # GET /records/1 or /records/1.json
  def show; end

  # GET /records/new
  def new
    @record = Record.new
    @groups = current_user.groups.where(user_id: current_user.id).order(:name)
  end

  # GET /records/1/edit
  def edit; end

  # POST /records or /records.json
  def create
    params = record_params
    @record = Record.new(user: current_user, name: params[:name], amount: params[:amount])

    respond_to do |format|
      if @record.save
        @group = Group.find(params[:group_id])
        @record.groups << @group
        format.html { redirect_to user_records_url(current_user, @record), notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to user_records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def record_params
    params.require(:record).permit(:user_id, :name, :amount, :group_id)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with model: @record, url: user_records_path, method: :post do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :group_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="mx-5">
    <% form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br />

  <div class="mx-5">
    <% form.label :amount, style: "display: block" %>
    <%= form.text_field :amount, class:"form-control", placeholder:"Amount" %>
  </div>
  <br />
  <br />

  <%= form.select :group_id, @groups&.map{ |group| [group.name, group.id] }, { :prompt => 'Select Group'}, class:"form-control mb-3" %> 

  <div class="mx-5 text-center ">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/records/_record.html.erb
<div class="group_id py-1" >
  <div class="flex">
    <p>
      <%= record.name %>
    </p>

    <p>
      <%= record.amount %>
    </p>
  </div>
  
  <p class="my-3 text-center">
    <%= link_to "Show this record",  user_record_path(current_user, record) %>
  </p>
</div>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Show this record", @record %> |
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Records</h1>
<% if @records.empty? %>
    <p class="text-center">No record added yet!</p>
  <% end %>

<div id="records">
  <% @records.each do |record| %>
    <%= render record %>
  <% end %>
</div>
<div class="text-center link-new"">
  <%= link_to "Add New record", new_user_record_path %>
</div>

app/views/records/new.html.erb
<h1 class="text-center">New record</h1>

<%= render "form", record: @record %>

<br>

<div class="text-center link-new">
  <%= link_to "Back to records", user_records_path %>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @record %>

<%= button_to "Delete this record", user_record_path, method: :delete, class: "btn btn-danger m-5" %>

<div class="link-new text-center">
  <%= link_to "Back to records", user_records_path %>
</div>